### PR TITLE
Fix: rename create_cache in plugin

### LINKED ISSUE #258: [BUG]: Duplicate create_cache
**Describe the bug**
We have two version of `create_cache` in [libCacheSim/bin/cachesim/cache_init.h](https://github.com/1a1a11a/libCacheSim/blob/c9f041efd4b488c447273c918c10f08be5e3c346/libCacheSim/bin/cachesim/cache_init.h#L17) and [libCacheSim/cache/plugin.c](https://github.com/1a1a11a/libCacheSim/blob/c9f041efd4b488c447273c918c10f08be5e3c346/libCacheSim/cache/plugin.c#L93)

```c

cache_t *create_cache(const char *const cache_alg_name,
common_cache_params_t cc_params, void *specific_params)


static inline cache_t *create_cache(const char *trace_path,
const char *eviction_algo,
const uint64_t cache_size,
const char *eviction_params,


```
This can cause conflicts when we attempt to load them simultaneously (although this is not common).

### PR DESCRIPTION
**Pull request by haochengxia**
Fix #258

### CODE REVIEW

File: libCacheSim/mrcProfiler/mrcProfiler.cpp [hunk 1]
```diff
@@ -305,7 +305,8 @@ void mrcProfiler::MRCProfilerMINISIM::run() {
                                        .default_ttl = 0,
                                        .hashpower = 20,
                                        .consider_obj_metadata = false};
-    caches[i] = create_cache(params_.cache_algorithm_str, cc_params, nullptr);
```
Comment (1a1a11a) [inline libCacheSim/mrcProfiler/mrcProfiler.cpp:308]: Do we need to update this?

Comment (haochengxia) [reply libCacheSim/mrcProfiler/mrcProfiler.cpp:308]: We can directly use `create_cache_internal` here

Comment (1a1a11a) [reply libCacheSim/mrcProfiler/mrcProfiler.cpp:308]: nvm
